---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbooot
  labels:
    app: springbooot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbooot
  template:
    metadata:
      labels:
        app: springbooot
    spec:
      containers:
        - name: springbooot
          image: docker.io/phengbunath/springbooot:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
